<?php

namespace Database\Seeders;

use App\Models\BlockType;
use Illuminate\Database\Seeder;

class BlockTypeSeeder extends Seeder
{
    public function run(): void
    {
        $activeSlugs = ['header', 'plain_text', 'section', 'container', 'cluster', 'grid', 'content_header', 'button_link', 'card', 'stat-card', 'alert', 'link-list', 'link-list-item', 'breadcrumb'];

        BlockType::query()
            ->whereNotIn('slug', $activeSlugs)
            ->update(['status' => 'draft']);

        collect([
            [
                'name' => 'Header',
                'slug' => 'header',
                'category' => 'content',
                'description' => 'Primitive translated heading text with a shared heading level.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 5,
                'status' => 'published',
            ],
            [
                'name' => 'Plain Text',
                'slug' => 'plain_text',
                'category' => 'content',
                'description' => 'Primitive translated paragraph text rendered as a plain paragraph element.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 6,
                'status' => 'published',
            ],
            [
                'name' => 'Section',
                'slug' => 'section',
                'category' => 'layout',
                'description' => 'Top-level layout wrapper for nested page blocks.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 2,
                'status' => 'published',
            ],
            [
                'name' => 'Container',
                'slug' => 'container',
                'category' => 'layout',
                'description' => 'Width-constrained layout wrapper for nested page blocks.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 3,
                'status' => 'published',
            ],
            [
                'name' => 'Cluster',
                'slug' => 'cluster',
                'category' => 'layout',
                'description' => 'Inline layout wrapper for grouping child blocks such as button links.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 4,
                'status' => 'published',
            ],
            [
                'name' => 'Grid',
                'slug' => 'grid',
                'category' => 'layout',
                'description' => 'Responsive grid wrapper for nested card and content blocks.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 5,
                'status' => 'published',
            ],
            [
                'name' => 'Content Header',
                'slug' => 'content_header',
                'category' => 'pattern',
                'description' => 'Docs-style content header with title, intro text, and optional metadata items.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 1,
                'status' => 'published',
            ],
            [
                'name' => 'Button Link',
                'slug' => 'button_link',
                'category' => 'content',
                'description' => 'Translated CTA label with a shared URL, target, and WebBlocks button variant.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 7,
                'status' => 'published',
            ],
            [
                'name' => 'Card',
                'slug' => 'card',
                'category' => 'content',
                'description' => 'Translated card content with optional shared link settings for grid-based feature sections.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 8,
                'status' => 'published',
            ],
            [
                'name' => 'Stat Card',
                'slug' => 'stat-card',
                'category' => 'content',
                'description' => 'Translated metric or stat card with eyebrow label, value, and description.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 9,
                'status' => 'published',
            ],
            [
                'name' => 'Link List',
                'slug' => 'link-list',
                'category' => 'navigation',
                'description' => 'WebBlocks UI link list container for structured navigation rows.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => true,
                'sort_order' => 11,
                'status' => 'published',
            ],
            [
                'name' => 'Link List Item',
                'slug' => 'link-list-item',
                'category' => 'navigation',
                'description' => 'One row in a WebBlocks UI link list with title, meta, description, and URL.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 12,
                'status' => 'published',
            ],
            [
                'name' => 'Alert',
                'slug' => 'alert',
                'category' => 'pattern',
                'description' => 'Translated alert or callout content with a shared WebBlocks UI alert variant.',
                'source_type' => 'static',
                'is_system' => false,
                'is_container' => false,
                'sort_order' => 10,
                'status' => 'published',
            ],
            [
                'name' => 'Breadcrumb',
                'slug' => 'breadcrumb',
                'category' => 'navigation',
                'description' => 'Renders the current page breadcrumb trail from the active site and translation context.',
                'source_type' => 'static',
                'is_system' => true,
                'is_container' => false,
                'sort_order' => 13,
                'status' => 'published',
            ],
        ])->each(fn (array $item) => BlockType::query()->updateOrCreate(['slug' => $item['slug']], $item));

        collect([
            'heading' => 'Heading',
            'text' => 'Text',
            'rich-text' => 'Rich Text',
            'quote' => 'Quote',
            'callout' => 'Callout',
            'code' => 'Code',
            'list' => 'List',
            'table' => 'Table',
            'accordion' => 'Accordion',
            'tabs' => 'Tabs',
            'faq' => 'FAQ',
            'image' => 'Image',
            'gallery' => 'Gallery',
            'slider' => 'Slider',
            'video' => 'Video',
            'audio' => 'Audio',
            'file' => 'File',
            'map' => 'Map',
            'menu' => 'Menu',
            'pagination' => 'Pagination',
            'toc' => 'TOC',
            'form' => 'Form',
            'button' => 'Button',
            'input' => 'Input',
            'textarea' => 'Textarea',
            'select' => 'Select',
            'checkbox-group' => 'Checkbox Group',
            'radio-group' => 'Radio Group',
            'submit' => 'Submit',
            'search' => 'Search',
            'contact_form' => 'Contact Form',
            'product-card' => 'Product Card',
            'product-grid' => 'Product Grid',
            'pricing' => 'Pricing',
            'cart-summary' => 'Cart Summary',
            'checkout-summary' => 'Checkout Summary',
            'social-links' => 'Social Links',
            'share-buttons' => 'Share Buttons',
            'testimonial' => 'Testimonial',
            'comments' => 'Comments',
            'stats' => 'Stats',
            'metric-card' => 'Metric Card',
            'logo-cloud' => 'Logo Cloud',
            'timeline' => 'Timeline',
            'feature-grid' => 'Feature Grid',
            'feature-item' => 'Feature Item',
            'comparison' => 'Comparison',
            'team' => 'Team',
            'faq-list' => 'FAQ List',
            'html' => 'HTML',
            'hero' => 'Hero',
            'cta' => 'CTA',
            'columns' => 'Columns',
            'column_item' => 'Column Item',
            'split' => 'Split',
            'stack' => 'Stack',
            'card-group' => 'Card Group',
            'page-title' => 'Page Title',
            'page-content' => 'Page Content',
            'page-meta' => 'Page Meta',
            'navigation-auto' => 'Navigation Auto',
            'auth-form' => 'Auth Form',
            'cookie-notice' => 'Cookie Notice',
        ])->each(function (string $name, string $slug): void {
            BlockType::query()->updateOrCreate(
                ['slug' => $slug],
                [
                    'name' => $name,
                    'category' => 'legacy',
                    'source_type' => 'static',
                    'is_system' => false,
                    'is_container' => false,
                    'sort_order' => 100,
                    'status' => 'draft',
                ],
            );
        });
    }
}
