<?php

namespace Tests\Feature\Console;

use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class PackageStatusCommandTest extends TestCase
{
  #[Test]
  public function package_status_command_is_registered_and_reports_package_resource_boundary_state_read_only(): void
  {
    $webblocksCmsRootOverride = is_file(config_path('webblocks-cms.php')) ? 'yes' : 'no';

    $this->artisan('list')
      ->expectsOutputToContain('webblocks:package-status')
      ->assertExitCode(0);

    $this->artisan('webblocks:package-status')
      ->expectsOutputToContain('Package: fklavyenet/webblocks-cms')
      ->expectsOutputToContain('Mode: read-only diagnostic only')
      ->expectsOutputToContain('Package resource boundary status')
      ->expectsOutputToContain('Package base path:')
      ->expectsOutputToContain('Package src path present: yes')
      ->expectsOutputToContain('Package config path present: yes')
      ->expectsOutputToContain('Package config files present: cms.php, contact.php, demo_media.php, webblocks-cms.php, webblocks-plugins.php, webblocks-updates.php')
      ->expectsOutputToContain('Expected package config defaults:')
      ->expectsOutputToContain('- webblocks-cms.php: package default=yes, root override='.$webblocksCmsRootOverride)
      ->expectsOutputToContain('- cms.php: package default=yes, root override=yes')
      ->expectsOutputToContain('- contact.php: package default=yes, root override=yes')
      ->expectsOutputToContain('- demo_media.php: package default=yes, root override=yes')
      ->expectsOutputToContain('- webblocks-plugins.php: package default=yes, root override=yes')
      ->expectsOutputToContain('- webblocks-updates.php: package default=yes, root override=yes')
      ->expectsOutputToContain('Package routes path present: yes')
      ->expectsOutputToContain('Package route files status: package files present (admin.php, auth.php, diagnostics.php, install.php, plugins/webblocks-ui-manager.php, public.php)')
      ->expectsOutputToContain('Package route Composer readiness: yes (provider discovery plus guarded route files)')
      ->expectsOutputToContain('Package source authority domains: CMS admin and public route trees; package-owned admin controllers, requests, support, and views for safely movable CMS runtime slices; package-owned public layout, page/search shells, and shipped public block renderers; package-owned CMS model foundation except the install-owned User model; package-owned shared admin partials and admin layout with root Blade wrappers preserved; package-owned seeder, stub, and movable public asset source files.')
      ->expectsOutputToContain('Expected package diagnostic route file exists: yes (diagnostics.php)')
      ->expectsOutputToContain('Package diagnostic route loading guard enabled: no (webblocks-cms.diagnostics.load_routes)')
      ->expectsOutputToContain('Package diagnostic route loaded in active runtime: no (webblocks-cms.diagnostics.package-status at /_webblocks-cms/diagnostics/package-status)')
      ->expectsOutputToContain('Expected package admin route file exists: yes (admin.php)')
      ->expectsOutputToContain('Package admin route file loading enabled: yes (webblocks-cms.admin.load_routes)')
      ->expectsOutputToContain('Package admin slice loaded in active runtime: no (admin.webblocks-cms.runtime-status at /webadmin/_webblocks-cms/runtime-status)')
      ->expectsOutputToContain('Package icon catalog admin routes loaded in active runtime: yes (admin.system.icons.index, admin.system.icons.update)')
      ->expectsOutputToContain('Expected package public route file exists: yes (public.php)')
      ->expectsOutputToContain('Package public route file loading enabled: yes (webblocks-cms.public.load_routes)')
      ->expectsOutputToContain('Package public slice loaded in active runtime: no (webblocks-cms.public.runtime-status at /_webblocks-cms/runtime-status)')
      ->expectsOutputToContain('Package public runtime routes loaded in active runtime: yes (home, localized.home, search, pages.show, contact-messages.store, public.privacy-consent.sync, admin-api.*)')
      ->expectsOutputToContain('Active runtime route loading remains root-authoritative: partial (install, auth, and profile stay root-owned while CMS admin and public runtime routes now load from the package).')
      ->expectsOutputToContain('Root route compatibility state: root routes now remain only for install, auth, profile, and project-level extension points.')
      ->expectsOutputToContain('Package resources/views path present: yes')
      ->expectsOutputToContain('Package view files status: package files present (')
      ->expectsOutputToContain('Package view Composer readiness: yes (provider discovery plus package view namespace)')
      ->expectsOutputToContain('Package admin slice view exists: yes (webblocks-cms::admin.runtime-status)')
      ->expectsOutputToContain('Package public slice view exists: yes (webblocks-cms::public.runtime-status)')
      ->expectsOutputToContain('Package icon catalog views present: yes (index.blade, edit-modal.blade)')
      ->expectsOutputToContain('Package admin runtime views present: yes (')
      ->expectsOutputToContain('Package shared admin partial views present: yes (audit-actor.blade, flash.blade, listing-filters.blade, page-actions.blade, page-header.blade, pagination.blade, form-actions.blade)')
      ->expectsOutputToContain('Root icon catalog view compatibility wrappers present: yes')
      ->expectsOutputToContain('Root admin runtime view compatibility wrappers present: yes')
      ->expectsOutputToContain('Root shared admin partial compatibility wrappers present: yes')
      ->expectsOutputToContain('Icon catalog view package authority state: yes (package controller renders webblocks-cms::admin.system.icons.index)')
      ->expectsOutputToContain('Shared admin partial package authority state: yes (package-owned admin views can render shared page headers, flash messages, listing filters, pagination, page actions, audit actor output, and form actions through the package namespace while root Blade wrappers remain available for compatibility).')
      ->expectsOutputToContain('Package public block renderer partials present: yes (70 files under package pages/partials/blocks)')
      ->expectsOutputToContain('Root public block renderer compatibility wrappers present: yes (70 matching root wrappers)')
      ->expectsOutputToContain('Public block renderer package authority state: yes (Block::publicRenderView() now prefers package block partials first; root pages.partials.blocks.* remains available for install-specific or custom fallback)')
      ->expectsOutputToContain('Root view compatibility state: mixed (admin layout, icon, public layout, public page shell, public search, slot entry views, and core public block renderers now render through the package namespace, while many admin wrappers and install-specific root block fallbacks remain root-accessible).')
      ->expectsOutputToContain('Package database/migrations path present: yes')
      ->expectsOutputToContain('Package migration boundary status: pilot files present')
      ->expectsOutputToContain('Package migration files status: package files present (')
      ->expectsOutputToContain('Package migration loading guard enabled: no (webblocks-cms.boundaries.load_migrations)')
      ->expectsOutputToContain('Package migrations loaded in active runtime: no')
      ->expectsOutputToContain('Legacy root migration compatibility state: yes (root database/migrations remains authoritative for source-maintained installs).')
      ->expectsOutputToContain('Package update migration readiness: package consumer System Updates use packages/webblocks-cms/database/migrations/updates when PHP migrations are present and skip host application migrations otherwise.')
      ->expectsOutputToContain('Detected System Update migration strategy: source (root composer.json owns WebBlocks\\Cms\\ autoloading from packages/webblocks-cms/src/)')
      ->expectsOutputToContain('Package database/seeders path present: yes')
      ->expectsOutputToContain('Package seeder boundary status: pilot files present')
      ->expectsOutputToContain('Package seeder files status: package files present (')
      ->expectsOutputToContain('Package catalog seeders present: yes (CoreCatalogSeeder, IconCatalogSeeder, PageTypeSeeder, LayoutTypeSeeder, SlotTypeSeeder)')
      ->expectsOutputToContain('Root catalog seeder compatibility wrappers present: yes')
      ->expectsOutputToContain('Package public path present: yes')
      ->expectsOutputToContain('Package public asset boundary status: pilot files present')
      ->expectsOutputToContain('Package public assets status: package files present (cms/brand/apple-touch-icon.png')
      ->expectsOutputToContain('Package public asset files present: yes (apple-touch-icon, favicon-16x16, favicon-32x32, icon-192x192, icon-512x512, logo-180, logo-32, logo-64, og-image')
      ->expectsOutputToContain('Package public asset publish readiness: yes (tag webblocks-cms-assets publishes package assets to public/cms)')
      ->expectsOutputToContain('Root compatibility public assets present: yes')
      ->expectsOutputToContain('Active public runtime asset URLs remain root compatibility paths: yes (package public layout still references root public/cms assets for active runtime compatibility)')
      ->expectsOutputToContain('Root runtime asset compatibility path: public/cms (active admin and public runtime asset URLs still resolve here).')
      ->expectsOutputToContain('Legacy root public asset compatibility state: yes (root public/cms and install-owned public/site remain the active runtime asset paths, even though the package now also carries the public layout CSS and JS plus admin CSS, JS, and CMS brand source files it needs).')
      ->expectsOutputToContain('Future package public asset Composer readiness: partial (package-owned public rendering assets plus admin CSS, JS, and CMS brand source files now exist, but current WebBlocks UI CDN pinning and root public/cms runtime asset flow stay unchanged).')
      ->expectsOutputToContain('Package stubs path present: yes')
      ->expectsOutputToContain('Package stub boundary status: pilot files present')
      ->expectsOutputToContain('Package stubs status: package files present (starter/composer.json.stub, starter/env.example.stub)')
      ->expectsOutputToContain('Package starter stubs present: yes (README, composer.json, env.example)')
      ->expectsOutputToContain('Package stub publish readiness: yes (tag webblocks-cms-stubs publishes starter stubs to stubs/vendor/webblocks-cms)')
      ->expectsOutputToContain('Starter stub readiness: yes (package-owned starter stubs are present; a separate starter package is still intentionally not created here).')
      ->expectsOutputToContain('Package service provider loaded: yes')
      ->expectsOutputToContain('Package view namespace registered: yes (webblocks-cms)')
      ->expectsOutputToContain('Package diagnostic view exists: yes (webblocks-cms::diagnostics.package-status)')
      ->expectsOutputToContain('Package low-risk runtime support moves present: yes (AdminPagination, BlockTypeIndexState, MediaIndexState, PageIndexState)')
      ->expectsOutputToContain('Root runtime support compatibility wrappers present: no (missing')
      ->expectsOutputToContain('Package icon runtime moves present: yes (SyncWebBlocksUiIconsCommand, IconCatalogController, IconCatalogItemUpdateRequest, IconCatalog, WebBlocksIconManifestSyncer)')
      ->expectsOutputToContain('Package admin runtime moves present: yes (')
      ->expectsOutputToContain('Root icon runtime compatibility wrappers present: no (missing')
      ->expectsOutputToContain('Root admin runtime compatibility wrappers present: no (missing')
      ->expectsOutputToContain('Package public model foundation moves present: yes (Block, ContactMessage, Locale, Page, PageSlot, PageTranslation, PublicSearchIndex, Site, SiteDomain, SystemSetting, VisitorEvent)')
      ->expectsOutputToContain('Root public model compatibility wrappers present: no (missing')
      ->expectsOutputToContain('Root compatibility wrappers: minimal host-owned app shell files for auth, install, profile, User, providers, and project-layer boundaries; small operational transition app files that still serve source-maintained install or legacy asset workflows; root Blade wrappers for moved admin/public views, layouts, and shared admin partials; root seeder wrappers for moved package seeders; root public/cms runtime copies that keep active asset URLs stable.')
      ->expectsOutputToContain('Public model foundation package authority state: yes (Block, ContactMessage, Locale, Page, PageSlot, PageTranslation, PublicSearchIndex, Site, SiteDomain, SystemSetting, and VisitorEvent now live under package Models without root App\\Models wrappers).')
      ->expectsOutputToContain('User model ownership state: root-owned permanently for now (User remains app-owned and was not moved into the package).')
      ->expectsOutputToContain('Icon catalog admin route package authority state: yes (admin.system.icons.index uses the package controller directly)')
      ->expectsOutputToContain('Core admin runtime package authority state: yes (Pages, Blocks, Media, Shared Slots, Navigation, Block Types, and Page Layouts now execute from package controllers, requests, support classes, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Site and Locale admin runtime package authority state: yes (Sites, Site Domains, Site Variables, and Locales now execute from package controllers, requests, support classes, models, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Operational admin runtime package authority state: yes (Dashboard, Contact Messages admin review, Visitor Reports, Slot Types, System Plugins, System Search, and System Settings now execute from package controllers, requests where applicable, support classes, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Icon catalog sync command package authority state: yes (icons:sync-webblocks-ui is registered by the package provider with the package command)')
      ->expectsOutputToContain('Package diagnostic view render check: not run (use --view-check)')
      ->expectsOutputToContain('Package Composer package name present: yes (fklavyenet/webblocks-cms)')
      ->expectsOutputToContain('Package Composer provider discovery present: yes (WebBlocks\\Cms\\WebBlocksCmsServiceProvider)')
      ->expectsOutputToContain('Package Composer seeder autoload present: yes (WebBlocks\\Cms\\Database\\Seeders\\)')
      ->expectsOutputToContain('Root Composer package name present: yes (fklavyenet/webblocks-cms)')
      ->expectsOutputToContain('Root Composer package type package-ready: yes (library)')
      ->expectsOutputToContain('Root Composer package autoload present: yes (WebBlocks\\Cms\\ => packages/webblocks-cms/src/)')
      ->expectsOutputToContain('Root Composer provider discovery present: yes (WebBlocks\\Cms\\WebBlocksCmsServiceProvider)')
      ->expectsOutputToContain('Target Composer install flow: composer require fklavyenet/webblocks-cms (tagged root package metadata now supports direct consumer installs, while the maintenance repo runtime remains authoritative for local source development).')
      ->expectsOutputToContain('Target Composer update flow: composer update fklavyenet/webblocks-cms followed by package-aware migration handling, catalog sync, block-types:sync-core, cache clear, asset publish or sync when needed, package diagnostics, and installed-version sync when release state is real.')
      ->expectsOutputToContain('Root migration/update/install/auth blockers: install, auth, and profile runtime remain host-owned; App\\Models\\User remains install-owned; root public/cms remains the active runtime asset compatibility path; root migration authority and root update/install operational flows remain authoritative.')
      ->expectsOutputToContain('Starter split readiness: not ready (package transition consolidation is complete for all safely movable CMS-owned source, but the remaining install/auth, User, root runtime asset path, and root migration or update authority blockers still prevent a starter split).')
      ->expectsOutputToContain('Starter foundation readiness: partial (root package metadata now supports direct Composer installation and provider discovery, while the maintenance repo still carries the remaining install/auth, User, root runtime asset path, and root migration or update authority blockers; fklavyenet/webblocks-cms-starter is intentionally not created yet).')
      ->expectsOutputToContain('Composer-managed update target note: future Composer-managed package updates remain the target boundary, while current root Composer and runtime update flow stay authoritative.')
      ->expectsOutputToContain('Transition note: root runtime remains authoritative unless a resource has been intentionally moved and wired.')
      ->expectsOutputToContain('This command performs no publishing, migrations, cache clearing, file writes, database writes, install-state changes, or update-state changes.')
      ->assertExitCode(0);
  }

  #[Test]
  public function package_status_command_can_optionally_render_the_package_diagnostic_view_through_the_namespace(): void
  {
    $this->artisan('webblocks:package-status --view-check')
      ->expectsOutputToContain('Package diagnostic route loaded in active runtime: no (webblocks-cms.diagnostics.package-status at /_webblocks-cms/diagnostics/package-status)')
      ->expectsOutputToContain('Package admin slice loaded in active runtime: no (admin.webblocks-cms.runtime-status at /webadmin/_webblocks-cms/runtime-status)')
      ->expectsOutputToContain('Package icon catalog admin routes loaded in active runtime: yes (admin.system.icons.index, admin.system.icons.update)')
      ->expectsOutputToContain('Package public slice loaded in active runtime: no (webblocks-cms.public.runtime-status at /_webblocks-cms/runtime-status)')
      ->expectsOutputToContain('Package public runtime routes loaded in active runtime: yes (home, localized.home, search, pages.show, contact-messages.store, public.privacy-consent.sync, admin-api.*)')
      ->expectsOutputToContain('Package diagnostic view exists: yes (webblocks-cms::diagnostics.package-status)')
      ->expectsOutputToContain('Package catalog seeders present: yes (CoreCatalogSeeder, IconCatalogSeeder, PageTypeSeeder, LayoutTypeSeeder, SlotTypeSeeder)')
      ->expectsOutputToContain('Package low-risk runtime support moves present: yes (AdminPagination, BlockTypeIndexState, MediaIndexState, PageIndexState)')
      ->expectsOutputToContain('Package icon runtime moves present: yes (SyncWebBlocksUiIconsCommand, IconCatalogController, IconCatalogItemUpdateRequest, IconCatalog, WebBlocksIconManifestSyncer)')
      ->expectsOutputToContain('Package admin runtime moves present: yes (')
      ->expectsOutputToContain('Package shared admin partial views present: yes (audit-actor.blade, flash.blade, listing-filters.blade, page-actions.blade, page-header.blade, pagination.blade, form-actions.blade)')
      ->expectsOutputToContain('Shared admin partial package authority state: yes (package-owned admin views can render shared page headers, flash messages, listing filters, pagination, page actions, audit actor output, and form actions through the package namespace while root Blade wrappers remain available for compatibility).')
      ->expectsOutputToContain('Package public model foundation moves present: yes (Block, ContactMessage, Locale, Page, PageSlot, PageTranslation, PublicSearchIndex, Site, SiteDomain, SystemSetting, VisitorEvent)')
      ->expectsOutputToContain('Root public model compatibility wrappers present: no (missing')
      ->expectsOutputToContain('Icon catalog admin route package authority state: yes (admin.system.icons.index uses the package controller directly)')
      ->expectsOutputToContain('Core admin runtime package authority state: yes (Pages, Blocks, Media, Shared Slots, Navigation, Block Types, and Page Layouts now execute from package controllers, requests, support classes, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Site and Locale admin runtime package authority state: yes (Sites, Site Domains, Site Variables, and Locales now execute from package controllers, requests, support classes, models, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Operational admin runtime package authority state: yes (Dashboard, Contact Messages admin review, Visitor Reports, Slot Types, System Plugins, System Search, and System Settings now execute from package controllers, requests where applicable, support classes, and view trees without root App\\... wrappers).')
      ->expectsOutputToContain('Icon catalog sync command package authority state: yes (icons:sync-webblocks-ui is registered by the package provider with the package command)')
      ->expectsOutputToContain('Package public asset publish readiness: yes (tag webblocks-cms-assets publishes package assets to public/cms)')
      ->expectsOutputToContain('Package public block renderer partials present: yes (70 files under package pages/partials/blocks)')
      ->expectsOutputToContain('Root compatibility public assets present: yes')
      ->expectsOutputToContain('Active public runtime asset URLs remain root compatibility paths: yes (package public layout still references root public/cms assets for active runtime compatibility)')
      ->expectsOutputToContain('Root runtime asset compatibility path: public/cms (active admin and public runtime asset URLs still resolve here).')
      ->expectsOutputToContain('Package stub publish readiness: yes (tag webblocks-cms-stubs publishes starter stubs to stubs/vendor/webblocks-cms)')
      ->expectsOutputToContain('Root migration/update/install/auth blockers: install, auth, and profile runtime remain host-owned; App\\Models\\User remains install-owned; root public/cms remains the active runtime asset compatibility path; root migration authority and root update/install operational flows remain authoritative.')
      ->expectsOutputToContain('Starter split readiness: not ready (package transition consolidation is complete for all safely movable CMS-owned source, but the remaining install/auth, User, root runtime asset path, and root migration or update authority blockers still prevent a starter split).')
      ->expectsOutputToContain('Starter foundation readiness: partial (root package metadata now supports direct Composer installation and provider discovery, while the maintenance repo still carries the remaining install/auth, User, root runtime asset path, and root migration or update authority blockers; fklavyenet/webblocks-cms-starter is intentionally not created yet).')
      ->expectsOutputToContain('Package diagnostic view render check: success')
      ->expectsOutputToContain('This command performs no publishing, migrations, cache clearing, file writes, database writes, install-state changes, or update-state changes.')
      ->assertExitCode(0);
  }
}
