<?php

namespace WebBlocks\Cms\Support\Blocks;

use WebBlocks\Cms\Models\BlockType;

class CoreBlockTypeCatalogSyncer
{
  public function sync(): array
  {
    $summary = [
      'created' => 0,
      'updated' => 0,
      'unchanged' => 0,
      'skipped' => 0,
    ];

    foreach ($this->definitions() as $definition) {
      $blockType = BlockType::query()->where('slug', $definition['slug'])->first();

      if (! $blockType) {
        BlockType::query()->create($definition);
        $summary['created']++;

        continue;
      }

      $changes = [];

      foreach ($this->updatableColumns() as $column) {
        if ($blockType->{$column} !== $definition[$column]) {
          $changes[$column] = $definition[$column];
        }
      }

      if ($changes === []) {
        $summary['unchanged']++;

        continue;
      }

      $blockType->forceFill($changes)->save();
      $summary['updated']++;
    }

    return $summary;
  }

  public function slugs(): array
  {
    return array_column($this->definitions(), 'slug');
  }

  public function definitions(): array
  {
    return [
      [
        'name' => 'Text',
        'slug' => 'text',
        'category' => 'legacy',
        'description' => 'Legacy transitional text block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 1,
        'status' => 'draft',
      ],
      [
        'name' => 'Header',
        'slug' => 'header',
        'category' => 'content',
        'description' => 'Primitive translated heading text with a shared heading level.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 5,
        'status' => 'published',
      ],
      [
        'name' => 'Plain Text',
        'slug' => 'plain_text',
        'category' => 'content',
        'description' => 'Primitive translated paragraph text rendered as a plain paragraph element.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 6,
        'status' => 'published',
      ],
      [
        'name' => 'Rich Text',
        'slug' => 'rich-text',
        'category' => 'content',
        'description' => 'Translated body copy with a small safe HTML subset for inline editorial formatting.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 6,
        'status' => 'published',
      ],
      [
        'name' => 'Section',
        'slug' => 'section',
        'category' => 'layout',
        'description' => 'Top-level layout wrapper for nested page blocks.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 2,
        'status' => 'published',
      ],
      [
        'name' => 'Container',
        'slug' => 'container',
        'category' => 'layout',
        'description' => 'Width-constrained layout wrapper for nested page blocks.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 3,
        'status' => 'published',
      ],
      [
        'name' => 'Cluster',
        'slug' => 'cluster',
        'category' => 'layout',
        'description' => 'Inline layout wrapper for grouping child blocks such as button links.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 4,
        'status' => 'published',
      ],
      [
        'name' => 'Grid',
        'slug' => 'grid',
        'category' => 'layout',
        'description' => 'Responsive grid wrapper for nested card and content blocks.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 5,
        'status' => 'published',
      ],
      [
        'name' => 'Content Header',
        'slug' => 'content_header',
        'category' => 'layout',
        'description' => 'Docs-style content header with a fixed H1 title, intro text, and optional metadata items.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 1,
        'status' => 'published',
      ],
      [
        'name' => 'Hero',
        'slug' => 'hero',
        'category' => 'content',
        'description' => 'Translated promo-style hero with shared presentation settings and managed button children.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 2,
        'status' => 'published',
      ],
      [
        'name' => 'Columns',
        'slug' => 'columns',
        'category' => 'content',
        'description' => 'Structured content section with translated intro copy and shared child column items.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 3,
        'status' => 'published',
      ],
      [
        'name' => 'Column Item',
        'slug' => 'column_item',
        'category' => 'content',
        'description' => 'Translated child item used by Columns for card, plain, and stats-style presentation.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 4,
        'status' => 'published',
      ],
      [
        'name' => 'Code',
        'slug' => 'code',
        'category' => 'content',
        'description' => 'Translated code snippet body with a shared optional syntax language label.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 7,
        'status' => 'published',
      ],
      [
        'name' => 'Button Link',
        'slug' => 'button_link',
        'category' => 'content',
        'description' => 'Translated CTA label with a shared URL, target, and WebBlocks button variant.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 7,
        'status' => 'published',
      ],
      [
        'name' => 'Card',
        'slug' => 'card',
        'category' => 'layout',
        'description' => 'Composable WebBlocks UI card shell that contains Card Header, Card Body, and Card Footer region blocks.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 8,
        'status' => 'published',
      ],
      [
        'name' => 'Card Header',
        'slug' => 'card_header',
        'category' => 'layout',
        'description' => 'Composable WebBlocks UI card header region for nested content blocks inside Card.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 8,
        'status' => 'published',
      ],
      [
        'name' => 'Card Body',
        'slug' => 'card_body',
        'category' => 'layout',
        'description' => 'Composable WebBlocks UI card body region for nested content blocks inside Card.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 8,
        'status' => 'published',
      ],
      [
        'name' => 'Card Footer',
        'slug' => 'card_footer',
        'category' => 'layout',
        'description' => 'Composable WebBlocks UI card footer region for nested content blocks inside Card.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 8,
        'status' => 'published',
      ],
      [
        'name' => 'Stat Card',
        'slug' => 'stat-card',
        'category' => 'content',
        'description' => 'Translated metric or stat card with eyebrow label, value, and description.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 9,
        'status' => 'published',
      ],
      [
        'name' => 'Image',
        'slug' => 'image',
        'category' => 'content',
        'description' => 'Media-backed image block with translated caption and alt text plus an optional shared link URL.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 10,
        'status' => 'published',
      ],
      [
        'name' => 'Gallery',
        'slug' => 'gallery',
        'category' => 'content',
        'description' => 'Ordered media gallery with translated title or description copy and a shared overlay viewer contract.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 11,
        'status' => 'published',
      ],
      [
        'name' => 'Download',
        'slug' => 'download',
        'category' => 'content',
        'description' => 'Download CTA backed by shared media with translated label or helper copy and a shared button variant.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 12,
        'status' => 'published',
      ],
      [
        'name' => 'File',
        'slug' => 'file',
        'category' => 'content',
        'description' => 'File resource card backed by shared media or URL with translated title and supporting copy.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 13,
        'status' => 'published',
      ],
      [
        'name' => 'Video',
        'slug' => 'video',
        'category' => 'content',
        'description' => 'Video block with translated title and copy plus a shared uploaded media source or external URL.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 14,
        'status' => 'published',
      ],
      [
        'name' => 'Audio',
        'slug' => 'audio',
        'category' => 'content',
        'description' => 'Audio block with translated title and copy plus a shared uploaded media source or external URL.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 15,
        'status' => 'published',
      ],
      [
        'name' => 'Table',
        'slug' => 'table',
        'category' => 'content',
        'description' => 'Structured table rows with optional header-row formatting.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 16,
        'status' => 'published',
      ],
      [
        'name' => 'Quote',
        'slug' => 'quote',
        'category' => 'content',
        'description' => 'Editorial quote or testimonial with optional attribution.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 17,
        'status' => 'published',
      ],
      [
        'name' => 'Link List',
        'slug' => 'link-list',
        'category' => 'navigation',
        'description' => 'WebBlocks UI link list container for structured navigation rows.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 18,
        'status' => 'published',
      ],
      [
        'name' => 'Link List Item',
        'slug' => 'link-list-item',
        'category' => 'navigation',
        'description' => 'One row in a WebBlocks UI link list with title, meta, description, and URL.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 19,
        'status' => 'published',
      ],
      [
        'name' => 'Navigation Auto',
        'slug' => 'navigation-auto',
        'category' => 'navigation',
        'description' => 'Compatibility navigation block that renders site navigation items for an assigned menu key.',
        'source_type' => 'navigation',
        'is_system' => true,
        'is_container' => false,
        'sort_order' => 19,
        'status' => 'published',
      ],
      [
        'name' => 'TOC',
        'slug' => 'toc',
        'category' => 'navigation',
        'description' => 'Table of contents built from anchored Header blocks on the same page.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 20,
        'status' => 'published',
      ],
      [
        'name' => 'Alert',
        'slug' => 'alert',
        'category' => 'pattern',
        'description' => 'Translated alert or callout content with a shared WebBlocks UI alert variant.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 21,
        'status' => 'published',
      ],
      [
        'name' => 'Contact Form',
        'slug' => 'contact_form',
        'category' => 'form',
        'description' => 'Translated contact form with shared submission routing and notification settings.',
        'source_type' => 'form',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 22,
        'status' => 'published',
      ],
      [
        'name' => 'Rating',
        'slug' => 'rating',
        'category' => 'system',
        'description' => 'System engagement block for collecting lightweight star ratings without comment text.',
        'source_type' => 'engagement',
        'is_system' => true,
        'is_container' => false,
        'sort_order' => 22,
        'status' => 'published',
      ],
      [
        'name' => 'Comments',
        'slug' => 'comments',
        'category' => 'system',
        'description' => 'System engagement block for moderated public comments stored outside editorial block copy.',
        'source_type' => 'engagement',
        'is_system' => true,
        'is_container' => false,
        'sort_order' => 22,
        'status' => 'published',
      ],
      [
        'name' => 'CTA',
        'slug' => 'cta',
        'category' => 'content',
        'description' => 'Translated promo-style call to action with shared variant settings and managed button children.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 23,
        'status' => 'published',
      ],
      [
        'name' => 'Feature Grid',
        'slug' => 'feature-grid',
        'category' => 'content',
        'description' => 'Structured feature section with translated intro copy and shared child feature items.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 24,
        'status' => 'published',
      ],
      [
        'name' => 'Feature Item',
        'slug' => 'feature-item',
        'category' => 'content',
        'description' => 'Translated child item used by Feature Grid for card-style feature presentation.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 25,
        'status' => 'published',
      ],
      [
        'name' => 'Breadcrumb',
        'slug' => 'breadcrumb',
        'category' => 'navigation',
        'description' => 'Renders the current page breadcrumb trail from the active site and translation context.',
        'source_type' => 'static',
        'is_system' => true,
        'is_container' => false,
        'sort_order' => 26,
        'status' => 'published',
      ],
      [
        'name' => 'Header Actions',
        'slug' => 'header-actions',
        'category' => 'navigation',
        'description' => 'Renders public header utility actions such as color mode and search controls.',
        'source_type' => 'static',
        'is_system' => true,
        'is_container' => false,
        'sort_order' => 27,
        'status' => 'published',
      ],
      [
        'name' => 'Navbar',
        'slug' => 'sticky-navbar',
        'category' => 'navigation',
        'description' => 'Primitive navbar wrapper that renders nav.wb-navbar and nested child blocks.',
        'source_type' => 'static',
        'is_system' => true,
        'is_container' => true,
        'sort_order' => 28,
        'status' => 'published',
      ],
      [
        'name' => 'Navbar Brand',
        'slug' => 'navbar-brand',
        'category' => 'navigation',
        'description' => 'Navbar brand link with optional logo, title, subtitle, and home URL fallback.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 29,
        'status' => 'published',
      ],
      [
        'name' => 'Navbar Navigation',
        'slug' => 'navbar-navigation',
        'category' => 'navigation',
        'description' => 'Navbar navigation menu rendered from CMS Navigation items using WebBlocks UI navbar link classes.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 30,
        'status' => 'published',
      ],
      [
        'name' => 'Sidebar Brand',
        'slug' => 'sidebar-brand',
        'category' => 'navigation',
        'description' => 'Renders the docs sidebar brand link inside the aside shell wrapper.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 31,
        'status' => 'published',
      ],
      [
        'name' => 'Sidebar Navigation',
        'slug' => 'sidebar-navigation',
        'category' => 'navigation',
        'description' => 'Renders docs sidebar navigation wrappers and accepts sidebar nav items or groups.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 32,
        'status' => 'published',
      ],
      [
        'name' => 'Sidebar Nav Item',
        'slug' => 'sidebar-nav-item',
        'category' => 'navigation',
        'description' => 'Renders one docs sidebar navigation link with optional icon and active matching.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 33,
        'status' => 'published',
      ],
      [
        'name' => 'Sidebar Nav Group',
        'slug' => 'sidebar-nav-group',
        'category' => 'navigation',
        'description' => 'Renders one collapsible docs sidebar navigation group with child sidebar nav items.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => true,
        'sort_order' => 34,
        'status' => 'published',
      ],
      [
        'name' => 'Search Form',
        'slug' => 'search-form',
        'category' => 'navigation',
        'description' => 'Public site search form that targets the current site and locale search route.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 36,
        'status' => 'published',
      ],
      [
        'name' => 'Sidebar Footer',
        'slug' => 'sidebar-footer',
        'category' => 'navigation',
        'description' => 'Renders the docs sidebar footer callout and version text inside the aside shell wrapper.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 35,
        'status' => 'published',
      ],
      [
        'name' => 'HTML (Trusted)',
        'slug' => 'html',
        'category' => 'advanced',
        'description' => 'Render trusted static HTML. Use Rich Text for normal body copy and Code for escaped snippets. Do not paste untrusted scripts or third-party embeds here.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 99,
        'status' => 'published',
      ],
      [
        'name' => 'Card Grid',
        'slug' => 'card-grid',
        'category' => 'legacy',
        'description' => 'Legacy transitional card grid block kept as a draft compatibility catalog row for imported packages.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 99,
        'status' => 'draft',
      ],
      [
        'name' => 'Tabs',
        'slug' => 'tabs',
        'category' => 'legacy',
        'description' => 'Legacy transitional tabs block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 100,
        'status' => 'draft',
      ],
      [
        'name' => 'Slider',
        'slug' => 'slider',
        'category' => 'legacy',
        'description' => 'Legacy transitional slider block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 101,
        'status' => 'draft',
      ],
      [
        'name' => 'Menu',
        'slug' => 'menu',
        'category' => 'legacy',
        'description' => 'Legacy transitional menu block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 102,
        'status' => 'draft',
      ],
      [
        'name' => 'FAQ List',
        'slug' => 'faq-list',
        'category' => 'legacy',
        'description' => 'Legacy transitional FAQ list block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 103,
        'status' => 'draft',
      ],
      [
        'name' => 'Showcase List',
        'slug' => 'showcase-list',
        'category' => 'legacy',
        'description' => 'Legacy transitional showcase list block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 104,
        'status' => 'draft',
      ],
      [
        'name' => 'Contact Info',
        'slug' => 'contact-info',
        'category' => 'legacy',
        'description' => 'Legacy transitional contact info block kept as a draft compatibility catalog row.',
        'source_type' => 'static',
        'is_system' => false,
        'is_container' => false,
        'sort_order' => 105,
        'status' => 'draft',
      ],
    ];
  }

  private function updatableColumns(): array
  {
    return [
      'name',
      'category',
      'description',
      'source_type',
      'is_system',
      'is_container',
      'sort_order',
      'status',
    ];
  }
}
