<?php

return [
    'product' => env('WEBBLOCKS_RELEASE_PRODUCT', 'webblocks-cms'),
    'package_prefix' => env('WEBBLOCKS_RELEASE_PACKAGE_PREFIX', 'webblocks-cms'),
    'default_channel' => env('WEBBLOCKS_RELEASE_DEFAULT_CHANNEL', 'stable'),
    'disk' => env('WEBBLOCKS_RELEASE_DISK', 'local'),
    'output_directory' => env('WEBBLOCKS_RELEASE_OUTPUT_DIRECTORY', 'releases/builds'),
    'downloads_directory' => env('WEBBLOCKS_RELEASE_DOWNLOADS_DIRECTORY', 'app/public/releases'),
    'downloads_url_prefix' => env('WEBBLOCKS_RELEASE_DOWNLOADS_URL_PREFIX', '/storage/releases'),
    'exclude_vendor' => env('WEBBLOCKS_RELEASE_EXCLUDE_VENDOR', true),
    'exclude_git_metadata' => env('WEBBLOCKS_RELEASE_EXCLUDE_GIT_METADATA', true),
    'publish' => [
        'enabled' => env('WEBBLOCKS_RELEASE_PUBLISH_ENABLED', true),
        'server_url' => env('WEBBLOCKS_RELEASE_PUBLISH_SERVER_URL', env('WEBBLOCKS_UPDATES_CLIENT_SERVER_URL', 'https://updates.webblocksui.com')),
        'token' => env('WEBBLOCKS_RELEASE_PUBLISH_TOKEN'),
        'timeout_seconds' => env('WEBBLOCKS_RELEASE_PUBLISH_TIMEOUT_SECONDS', 30),
        'connect_timeout_seconds' => env('WEBBLOCKS_RELEASE_PUBLISH_CONNECT_TIMEOUT_SECONDS', 5),
    ],
    'exclude' => [
        '.git',
        '.github',
        '.ddev',
        '.env',
        '.env.*',
        '.fleet',
        '.idea',
        '.nova',
        '.phpunit.cache',
        '.phpunit.result.cache',
        '.vscode',
        '.zed',
        'auth.json',
        'node_modules',
        'vendor',
        'bootstrap/cache/*.php',
        'storage/app/public/assets/*',
        'storage/app/public/media/*',
        'storage/app/releases/*',
        'storage/framework/cache/*',
        'storage/framework/sessions/*',
        'storage/framework/testing/*',
        'storage/framework/views/*',
        'storage/logs/*',
        'storage/pail',
        'public/hot',
        'public/build',
        'public/storage',
        '*.log',
        '.DS_Store',
        'Thumbs.db',
    ],
];
