<?php

return [
    'enabled' => env('WEBBLOCKS_UPDATES_ENABLED', true),
    'server_url' => env('WEBBLOCKS_UPDATES_SERVER_URL', 'https://updates.webblocksui.com'),
    'channel' => env('WEBBLOCKS_UPDATES_CHANNEL', 'stable'),
    'api_version' => '1',
    'product' => 'webblocks-cms',
    'current_version' => env('APP_VERSION', '0.1.5'),
    'site_url' => env('APP_URL', 'http://localhost'),
    'instance_id' => env('WEBBLOCKS_UPDATES_INSTANCE_ID'),
    'timeout_seconds' => env('WEBBLOCKS_UPDATES_TIMEOUT_SECONDS', 5),
    'connect_timeout_seconds' => env('WEBBLOCKS_UPDATES_CONNECT_TIMEOUT_SECONDS', 3),
    'retry_times' => env('WEBBLOCKS_UPDATES_RETRY_TIMES', 0),
    'retry_sleep_milliseconds' => env('WEBBLOCKS_UPDATES_RETRY_SLEEP_MS', 150),
    'installer' => [
        'target_path' => env('WEBBLOCKS_UPDATE_TARGET_PATH', base_path()),
        'workspace_root' => env('WEBBLOCKS_UPDATE_WORKSPACE_ROOT', 'app/system-updates'),
        'download_timeout_seconds' => env('WEBBLOCKS_UPDATE_DOWNLOAD_TIMEOUT_SECONDS', 120),
        'command_timeout_seconds' => env('WEBBLOCKS_UPDATE_COMMAND_TIMEOUT_SECONDS', 600),
        'lock_name' => env('WEBBLOCKS_UPDATE_LOCK_NAME', 'system-updates:run'),
        'lock_ttl_seconds' => env('WEBBLOCKS_UPDATE_LOCK_TTL_SECONDS', 900),
        'excluded_paths' => [
            '.git',
            '.github',
            '.ddev',
            'storage',
            'bootstrap/cache',
            'node_modules',
            'vendor',
            'public/storage',
            'public/build',
        ],
    ],
];
